# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='./myapp/static/images/')),
                ('brand_info', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mall_name', models.CharField(max_length=255)),
                ('mall_in_area', models.CharField(max_length=255)),
                ('mall_location', models.CharField(max_length=255)),
                ('on_discount', models.BooleanField(default=False)),
                ('mall_discount', models.FloatField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('mall_info', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_location', models.CharField(max_length=255)),
                ('store_phone', models.CharField(blank=True, max_length=11)),
                ('store_site', models.CharField(blank=True, max_length=255)),
                ('on_discount', models.BooleanField(default=False)),
                ('store_discount', models.FloatField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('store_info', models.TextField(blank=True, default='', null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=11)),
                ('user_name', models.CharField(max_length=255)),
                ('user_sex', models.CharField(choices=[('male', '男'), ('female', '女'), ('others', '其他')], max_length=10, null=True)),
                ('user_password', models.CharField(max_length=255)),
                ('is_business_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.AddField(
            model_name='store',
            name='mall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Mall'),
        ),
    ]
