# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mall',
            name='mall_in_area',
            field=models.CharField(choices=[('海淀区', '海淀区'), ('朝阳区', '朝阳区'), ('西城区', '西城区'), ('东城区', '东城区'), ('丰台区', '丰台区'), ('昌平区', '昌平区')], max_length=255),
        ),
    ]
