# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160526_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='mall_jing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mall',
            name='mall_wei',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
