# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20160526_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mall',
            old_name='mall_jing',
            new_name='mall_latitude',
        ),
        migrations.RenameField(
            model_name='mall',
            old_name='mall_wei',
            new_name='mall_longitude',
        ),
    ]
