# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20160526_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('其他', '其他')], max_length=10, null=True),
        ),
    ]
