# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20160527_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mall',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='mall_discount',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='on_discount',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='start_time',
        ),
    ]
