# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20160528_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mall',
            name='mall_latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mall',
            name='mall_longitude',
            field=models.FloatField(),
        ),
    ]
