# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20160528_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_phone',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_site',
        ),
    ]
